id: P451F1778
initial_creation_type: ocr
source_metadata:
  volumes:
    8ed3b3a15d7841708961d214e51ec951:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
